---
title: "DEA of Tregs"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(Matrix)
library(Seurat)
library(SeuratObject)
library(dplyr)
library(ggplot2)
library(tidyverse)
library(gridExtra)
library(grid)
```

# Read data from files and put them into SeuratObjects
```{r}
meta.data <- read.table(
  'skin.tregs.meta.tsv',
  sep = '\t',
  quote = '',
  header = TRUE,
  row.names = 'X'
)
raw <- read.table(
  'skin.tregs.exp.tsv',
  sep = '\t',
  quote = '',
  header = TRUE,
  row.names = 'X'
)
corrected <- read.table(
  'skin.tregs.exp.recombatseq.tsv',
  sep = '\t',
  quote = '',
  header = TRUE
)
```
```{r}
seurat.raw <- CreateSeuratObject(
  counts = as.sparse(t(raw)),
  meta.data = meta.data
)
seurat.corrected <- CreateSeuratObject(
  counts = as.sparse(corrected),
  meta.data = meta.data
)
```
```{r}
# assign ident as healthy and disease
re.ident <- function(seurat.obj, column, old_true_id, new_true_id, new_false_id) {
  Idents(
    seurat.obj,
    cells = rownames(
      subset(
        seurat.obj@meta.data, 
        subset = endsWith(seurat.obj@meta.data[[column]], old_true_id)
      )
    )
  ) <- new_true_id
  Idents(
    seurat.obj,
    cells = rownames(
      subset(
        seurat.obj@meta.data, 
        subset = !endsWith(seurat.obj@meta.data[[column]], old_true_id)
      )
    )
  ) <- new_false_id
  return(seurat.obj)
}

seurat.raw <- re.ident(seurat.raw, 'status', 'normal', 'Healthy', 'Disease')
seurat.corrected <- re.ident(seurat.corrected, 'status', 'normal', 'Healthy', 'Disease')
```

```{r}
compute.de.genes <- function(seurat.obj, ident.1, ident.2, latent.vars = NULL) {
  # MAST requires lognorm data see https://www.bioconductor.org/packages/release/bioc/vignettes/MAST/inst/doc/MAST-interoperability.html#21_From_scater_to_MAST
  seurat.obj <- NormalizeData(
    seurat.obj,
    normalization.method = 'LogNormalize',
    scale.factor = 10000
  )
  de.genes <- FindMarkers(
    seurat.obj,
    ident.1 = ident.1,
    ident.2 = ident.2,
    assay = "RNA",
    test.use = 'MAST',
    slot = "data",
    min.pct = 0.1,
    logfc.threshold = 0,
    latent.vars = latent.vars
  )
  lfc.threshold <- 0.5
  pval.threshold <- 0.001
  de.genes['significant'] <- de.genes$p_val_adj < pval.threshold & abs(de.genes$avg_log2FC) > lfc.threshold
  de.genes['gene'] <- rownames(de.genes)
  return(de.genes)
}

raw.degs <- compute.de.genes(seurat.raw, 'Disease', 'Healthy')
corrected.degs <- compute.de.genes(seurat.corrected, 'Disease', 'Healthy')
```

```{r, fig.height = 20, fig.width = 10}
library(ggrepel)
plot.volcano <- function(de.genes, title, abs.xlim = 15) {
  lfc.threshold <- 0.5
  pval.threshold <- 0.001
  g <- ggplot(
    de.genes, 
    aes(x = avg_log2FC, y = -log10(p_val_adj), color = significant)
  ) + 
  geom_point() +
  ggtitle(title) +
  geom_vline(xintercept = c(-lfc.threshold, lfc.threshold), linetype = 'dashed') + 
  geom_hline(yintercept = -log10(pval.threshold), linetype = 'dashed') +
  scale_x_continuous(limits = c(-abs.xlim, abs.xlim)) + 
  geom_label_repel(
    aes(label = gene), 
    size = 3, 
    data = . %>% filter(significant),
    max.overlaps = 20
  )
  return(g)
}

plot.volcano(raw.degs, 'tregs.raw')
plot.volcano(corrected.degs, 'tregs.corrected')
```

```{r}
write.de.results <- function(de.genes, filename, significant.only) {
  if (significant.only) {
    de.genes <- de.genes %>% subset(subset = significant)
  }
  de.genes %>%
    write.table(
      filename,
      row.names = FALSE,
      quote = FALSE,
      sep = '\t'
    )
}
write.de.results(raw.degs, 'skin.tregs.exp.de.all.tsv', FALSE)
write.de.results(corrected.degs, 'skin.tregs.exp.recombatseq.de.all.tsv', FALSE)
```